#+TITLE: Nouvelles impressions d’Afrique
#+OPTIONS: toc:nil

#  NOTE: Compile this with tufte!

#+BEGIN_LaTeX

\marginnote{This is a random margin note. Notice that there isn't a number preceding the note, and there is no number in the main text where this note was written. Use \texttt{sidenote} to use a number.}

#+END_LaTeX

« De toutes les oeuvres de Raymond Roussel aucune, peut-être, ne reste aussi énigmatique que les Nouvelles impressions d’Afrique[fn:: Michel Leiris, « Autour des Nouvelles impressions d’Afrique », Roussel l’ingénu, 1987, p. 45. Raymond Roussel, Nouvelles impressions d’Afrique, 1963 : dorénavant appelé NIA. L’ouvrage a récemment été réédité par les soins de Jacques Sivan aux Éditions Al Dante (2004) dans le plus grand respect de la première édition, mais en donnant forme au souhait exprimé par Roussel d’utiliser des couleurs à la place des parenthèses. L’édition originale de NIA est mise à la disposition du public sur le site de la BnF : <http://gallica.bnf.fr/ark:/12148/bpt6k108582f.r=raymond+roussel.langES>. L’ouvrage a aussi été numérisé par Hibouc, avec les illustrations, mais sans respecter l’édition originale : <http://www.hibouc.net/lib/roussel-nouvelles-impressions-afrique-1.swf>. Les lecteurs anglophones peuvent consulter en ligne la traduction réalisée par Andrew Hugill au sein du Centre de Recherche en musique technologie et innovation de l’Université de Montford : <http://www.mti.dmu.ac.uk/~ahugill/nia/introduction.html>. Il s’agit d’un hypertexte certes élémentaire, mais qui donne une idée claire de la complexité de NIA.]. » Au caractère déroutant de cet ouvrage contribue notamment la quantité d’éléments non strictement linguistiques qui enveloppent le texte : un imposant emboîtement de parenthèses, de multiples notes infrapaginales dont la longueur dépasse souvent celle du texte principal, un pliage tout à fait particulier des feuillets qui composent le volume (cf. ci-après) et cinquante-neuf illustrations[fn:: Sur le site du sculpteur Jean-Louis Faure, on peut voir les cinquante-neuf illustrations de NIA avec les indications données par Roussel à l’illustrateur Henri-A. Zo : <http://emamo.free.fr/text_en/roussel.htm>.
] qui alternent avec autant de pages de texte. L’histoire aux teintes de mystère qui les entoure, et qui convient si bien au personnage de Roussel, fait des illustrations le plus mystérieux de ces éléments. Elles posent, en effet, à la critique des questions qui resteront sans doute encore longtemps sans solution et face auxquelles on ne peut qu’avancer des hypothèses plus ou moins vraisemblables, selon les cas ; la plus importante concernerait l’adéquation des illustrations à ce texte.

Pour des raisons qui nous échappent, Roussel a livré à ses lecteurs le plus complexe de ses livres sous la forme d’un volume illustré, conçu en toute première instance pour être vu davantage que pour être lu. À cela les illustrations contribuent de manière décisive, certes en occupant la moitié du volume, mais surtout par les rapports structuraux qu’elles entretiennent avec le reste des éléments qui configurent le paratexte des NIA.

Enfin, j’essayerai de montrer qu’au-delà du gonflage d’un volume, considéré trop mince, et du simple rôle décoratif, qu’elles remplissent très mal, les illustrations tiennent dans NIA un rôle structurant et qu’elles deviennent un élément important de lisibilité en contribuant à renforcer les réglages matériels du texte. [fn:: from: http://www.erudit.org/revue/etudlitt/2010/v41/n2/045167ar.html]

* L’histoire des illustrations
:PROPERTIES:
:ID:       611151F1-28B1-48A4-943D-48BF5E50825B
:END:


Les illustrations ont longtemps été considérées comme un élément purement accessoire dans NIA ; ainsi, Jean Ferry, dans l’édition Pauvert de 1963, leur avait conféré, en les regroupant à la fin du livre, un caractère tout à fait indépendant du texte, n’hésitant pas à parler, dans une note explicative, « d’illustrations fantômes », puisque destinées à rester entre les pages non coupées du volume[fn:: Cf. Raymond Roussel, Nouvelles impressions d’Afrique, op. cit., p. 89.]. Roussel aurait pris les décisions concernant le brochage du volume, l’ajout des illustrations et la réédition de « Mon âme » au dernier moment, confronté à l’évidente minceur d’un texte de seulement soixante-dix pages [fn:: Sur cette question, on se reportera à la biographie de François Caradec, Raymond Roussel, 1997, p. 365-sq.].

Il faudra attendre d’avoir analysé minutieusement les manuscrits de NIA, récemment mis à la disposition du public par la Bibliothèque nationale de France[fn:: Les quatorze années qui se sont écoulées depuis la découverte des manuscrits de NIA en 1991, jusqu’à leur mise en ordre par la BnF en 2005, donnent aussi une idée des difficultés que pose cet ouvrage.], pour établir la genèse du volume et, éventuellement, le moment exact de l’apparition des images ; pour l’heure, dans les premiers parcours que j’ai pu faire de ces documents, je n’ai réussi à repérer aucune référence aux illustrations, et les risques qu’ils n’en comportent aucune sont élevés.


Ces manuscrits montrent que, pour une grande partie, la rédaction du dernier ouvrage était déjà très avancée vers 1918, et qu’en 1927 Eugène Vallée, le prote de Lemerre qui s’était occupé de la plupart des livres de Roussel, travaillait déjà à la composition du volume dont la première édition porte le 30 juin 1932 comme date d’achevé d’imprimer[fn:: Roussel fixe dans son ouvrage posthume Comment j’ai écrit certains de mes livres (Paris, Pauvert, 1963 [Paris, Lemerre, 1935]) les dates d’écriture de NIA entre 1915 et 1928. Mais les documents du Fonds Roussel de la BnF permettent, aujourd’hui, de savoir que la composition matérielle du volume débute déjà en 1927 et elle est pratiquement terminée en 1931. Du travail réalisé par l’auteur pendant ces quinze années, la BnF conserve cent soixante feuillets autographes et dactylographiés. Cf. Annie Angremy, « La malle Roussel du bric à brac au décryptage », Revue de la BN. Découvrir Raymond Roussel, nº 43 (printemps 1992), p. 37-49 ; Laurent Busine, Raymond Roussel. Contemplator Enim, 1995, p. 21.]. La mise au point matérielle du volume se prolonge donc plus de quatre années, pendant lesquelles l’auteur aurait largement eu le temps d’en méditer la forme finale, pour le moins recherchée. Il est difficile d’imaginer Roussel s’adonnant, pour une telle tâche, aux plaisirs de l’improvisation.


La genèse de la commande des cinquante-neuf images qui accompagnent le texte à travers l’agence de détectives Goron au dessinateur Henri-Achille Zo[fn:: François Caradec, Raymond Roussel, op. cit., p. 365-sq. Le biographe rappelle que Henri-A. Zo avait illustré le roman de Pierre Loti, Ramuntcho, et l’admiration que Roussel portait à cet auteur pourrait avoir compté à l’heure de choisir justement ce dessinateur.] que Roussel, lui, ne rencontrera jamais, aurait donc été longuement mûrie. Laurent Busine en a donné une interprétation assez plausible :

#+BEGIN_QUOTE
[...] je pense que Raymond Roussel préméditait scrupuleusement cette commande, mais qu’il n’a pu en établir avec précision les termes qu’une fois les quatre chants des Nouvelles impressions d’Afrique composés. Il sut à ce moment combien de pages de texte le livre comporterait et donc combien de dessins il devait commander ; Raymond Roussel put alors déterminer, grâce à la pagination, quelles illustrations il désirait voir exécuter, quels sujets précisément il choisirait[fn:: Laurent Busine, Raymond Roussel. Contemplator Enim,op. cit., p. 17.].
#+END_QUOTE

L’idée d’une lente préméditation de la commande posée par Laurent Busine relève de l’hypothèse vraisemblable, mais pour ne s’en tenir qu’aux faits il convient d’insister, comme il n’hésite pas à le faire, d’ailleurs, sur l’expérience éditoriale de Roussel qui avait publié tous ses livres précédents chez le même éditeur à compte d’auteur (des éditions qui contribuèrent sans doute à sa ruine financière, les Nouvelles impressions étant en ce sens comme les premières des « impressions à fric ») et dont on sait qu’il se montrait extrêmement attentif au moindre détail concernant la publication de chacune de ses oeuvres. Quand il s’apprête à publier NIA, Roussel est donc un auteur qui a une bonne connaissance des processus de composition d’un volume et qui ne saurait se montrer indifférent aux questions touchant au brochage, au pliage d’un livre qui lui avait coûté tant d’efforts. « Il fallait [par exemple] que Raymond Roussel connaisse avec exactitude la présentation des pages imprimées, la disposition du texte et des notes… pour décider des images à faire réaliser[fn:: Id.] », de manière à ce que chaque illustration corresponde à des vers sélectionnés dans la page de texte qui la précédait.
* Just a sidenote - edited AGAIN

In English.

To see updating.

Pour des raisons qui nous échappent, Roussel a livré à ses lecteurs le plus complexe de ses livres sous la forme d’un volume illustré, conçu en toute première instance pour être vu davantage que pour être lu. À cela les illustrations contribuent de manière décisive, certes en occupant la moitié du volume, mais surtout par les rapports structuraux qu’elles entretiennent avec le reste des éléments qui configurent le paratexte des NIA.

Enfin, j’essayerai de montrer qu’au-delà du gonflage d’un volume, considéré trop mince, et du simple rôle décoratif, qu’elles remplissent très mal, les illustrations tiennent dans NIA un rôle structurant et qu’elles deviennent un élément important de lisibilité en contribuant à renforcer les réglages matériels du texte. [fn:: from: http://www.erudit.org/revue/etudlitt/2010/v41/n2/045167ar.html]

« De toutes les oeuvres de Raymond Roussel aucune, peut-être, ne reste aussi énigmatique que les Nouvelles impressions d’Afrique[fn:: Michel Leiris, « Autour des Nouvelles impressions d’Afrique », Roussel l’ingénu, 1987, p. 45. Raymond Roussel, Nouvelles impressions d’Afrique, 1963 : dorénavant appelé NIA. L’ouvrage a récemment été réédité par les soins de Jacques Sivan aux Éditions Al Dante (2004) dans le plus grand respect de la première édition, mais en donnant forme au souhait exprimé par Roussel d’utiliser des couleurs à la place des parenthèses. L’édition originale de NIA est mise à la disposition du public sur le site de la BnF : <http://gallica.bnf.fr/ark:/12148/bpt6k108582f.r=raymond+roussel.langES>. L’ouvrage a aussi été numérisé par Hibouc, avec les illustrations, mais sans respecter l’édition originale : <http://www.hibouc.net/lib/roussel-nouvelles-impressions-afrique-1.swf>. Les lecteurs anglophones peuvent consulter en ligne la traduction réalisée par Andrew Hugill au sein du Centre de Recherche en musique technologie et innovation de l’Université de Montford : <http://www.mti.dmu.ac.uk/~ahugill/nia/introduction.html>. Il s’agit d’un hypertexte certes élémentaire, mais qui donne une idée claire de la complexité de NIA.]. » Au caractère déroutant de cet ouvrage contribue notamment la quantité d’éléments non strictement linguistiques qui enveloppent le texte : un imposant emboîtement de parenthèses, de multiples notes infrapaginales dont la longueur dépasse souvent celle du texte principal, un pliage tout à fait particulier des feuillets qui composent le volume (cf. ci-après) et cinquante-neuf illustrations[fn:: Sur le site du sculpteur Jean-Louis Faure, on peut voir les cinquante-neuf illustrations de NIA avec les indications données par Roussel à l’illustrateur Henri-A. Zo : <http://emamo.free.fr/text_en/roussel.htm>.
] qui alternent avec autant de pages de texte. L’histoire aux teintes de mystère qui les entoure, et qui convient si bien au personnage de Roussel, fait des illustrations le plus mystérieux de ces éléments. Elles posent, en effet, à la critique des questions qui resteront sans doute encore longtemps sans solution et face auxquelles on ne peut qu’avancer des hypothèses plus ou moins vraisemblables, selon les cas ; la plus importante concernerait l’adéquation des illustrations à ce texte.
