* Ιστορία

http://www.greek-language.gr/greekLang/literature/anthologies/new/show.html?id=269

** Ο ΞΕΠΕΣΜΕΝΟΣ ΔΕΡΒΙΣΗΣ - πολυτονικά


Δύο, τρεῖς, πέντε, δέκα σταλαγμοί.

Ὅμοιοι μὲ τὸ μονότονον βῆμα τοῦ ἀγρύπνου ναύτου φρουροῦ εἰς τὴν κουβέρταν. Πλέει εἰς μαῦρα πέλαγα καὶ βλέπει οὐρανὸν καὶ θάλασσαν ἀγρίως χορεύουσαν, καὶ τυλιγμένος εἰς τὴν καπόταν του διασχίζει ἀκαριαίως τὸ σκότος μὲ τὴν ἐξανάπτουσαν καὶ ὑποσβήνουσαν λαμπυρίδα τοῦ τσιγάρου του.

Οἱ πετεινοὶ δὲν εἶχαν λαλήσει τὸ τρίτον λάλημα. Ἴσως εἶχαν τρομάξει ἀπὸ τὴν βαθεῖαν, θρηνώδη φωνὴν τοῦ σαλεπτσῆ, ὅστις εἶχεν ἀρχίσει τὸ φθινόπωρον, νύκτα βαθιά, νὰ κράζῃ. Ἦτο ὡς κρωγμὸς ἀγνώστου ὀρνέου, τὸ ὁποῖον εἶχε χάσει τὸν ἀέρα του, καὶ εἶχεν ἐνσκήψει μέσα εἰς τὴν πόλιν, κ' ἐζήτει ἁρπάγματα νὰ σπαράξη.

− Ζεστό! Βράζει!…

Ἔβραζεν, ἔβραζε, νύκτα βαθιά. Ζεστὸν τὸ σαλέπι, πολὺ ζεστότερον τὸ στρῶμα. Μόνον ἡ φωνὴ τοῦ σαλεπτσῆ ἐτρόμαζε τοὺς πετεινούς.

Εἶχε βρέξει ὀλίγον, εἶτα ᾐθρίασε. Σταλαγμοί, σταλαγμοὶ ἔπεφταν ἀργὰ−ἀργά, ἀπὸ τὴν ὑδρορρόην ἐντὸς τῆς αὐλῆς.

⁂
− Ἔ! καὶ ποῦ, σ' αὐτὸν τὸν κόσμο;

Ἡ ἐπιφώνησις ἠκούσθη εἰς τὸ σκότος ἀπὸ τὸ στόμα τοῦ σαλεπτσῆ.

Τὸ παράθυρον ἔτριξε, κράκ! ἀπὸ τὸ χαμηλὸν δωμάτιον τὸ βλέπον πρὸς τὸν δρόμον. Ἄνθρωπος προέκυψε τυλιγμένος μὲ σάλι. Ἔτεινε μέγαν κύαθον πρὸς τὸν σαλεπτσήν, ἀλλ' οὗτος ἠργοπόρει.

Ὁ ἄνθρωπος ἔκυψε νὰ ἰδῇ.

Ὑψηλὴ μορφή, μὲ λευκὸν σαρίκι, μὲ μαύρην χλαῖναν καὶ χιτῶνα χρωματιστόν, εἶχε σταθῆ ἐνώπιον τοῦ σαλεπτσῆ.

− Ποῦ, σ' αὐτὸν τὸν κόσμο;

− Μποὺ ντουνιὰ τσὰρκ φιλέκ.

− Ἄσκ ὀλσούν… ὑπεψιθύρισεν ὁ σαλεπτσής.

Δὲν εἶχε γνωρίσει τὸν ἄνθρωπον, ἀλλὰ τὸ ἔνδυμα. Κάθε ἄλλος θὰ τὸν ἐξελάμβανεν ὡς φάντασμα. Ἀλλ' αὐτὸς δὲν ἐπτοήθη. Ἦτο ἀπ' ἐκεῖνα τὰ χώματα.

⁂s
Εἶχεν ἀναφανῆ. Πότε; Πρὸ ἡμερῶν, πρὸ ἑβδομάδων. Πόθεν; Ἀπὸ τὴν Ρούμελην, ἀπὸ τὴν Ἀνατολήν, ἀπὸ τὴν Σταμπούλ. Πῶς; Ἐκ ποίας ἀφορμῆς; Ποῖος;

Ἦτον Δερβίσης; Ἦτον βεκτασής, χόντζας, ἰμάμης; Ἦτον οὐλεμάς, διαβασμένος; Ὑψηλός, μελαψός, συμπαθής, γλυκύς, ἄγριος. Μὲ τὸ σαρίκι του, μὲ τὸν τσουμπέν του, μὲ τὸν δουλαμάν του.

Ἦτο εἰς εὔνοιαν, εἰς δυσμένειαν; Εἶχεν ἀκμάσει, εἶχεν ἐκπέσει, εἶχεν ἐξορισθῇ; Μποὺ ντουνιὰ τσὰρκ φιλέκ. Αὐτὸς ὁ κόσμος εἶναι σφαῖρα καὶ γυρίζει.

Ἐκείνην τὴν βραδιὰν τὸν εἶχε προσκαλέσει μία παρέα. Ἑπτὰ ἢ ὀκτὼ φίλοι ἀχώριστοι. Ἀγαποῦσαν τὴν ζωήν, τὰ νιᾶτα. Ὁ ἕνας ἀπ' αὐτοὺς ἔβαλλε γιουβέτσι κάθε βράδυ. Οἱ ἄλλοι ἔτρωγαν.

Ἦτον λοταρτζὴς κ' ἐκέρδιζε δέκα ἢ δεκαπέντε δραχμὰς τὴν ἡμέραν. Τί νὰ τὰς κάμῃ; Τοὺς ἔβαλλε γιουβέτσι καὶ τοὺς ἐφίλευε. Ἦσαν λοτοφάγοι, μὲ ὀμικρὸν καὶ μὲ ὠμέγα.

Ἀγαποῦσαν τὰ τραγούδια, τὰ ὄργανα. Ὁ Δερβίσης δὲν ἔπινε κρασί, ἔπινε μαστίχαν. Δερβισάδες ἦσαν κι αὐτοί. Τοῦ εἶπαν νὰ τραγουδήσῃ. Ἐτραγούδησε. Τοῦ εἶπαν νὰ παίξῃ τὸ νάϊ. Ἔπαιξε.

Δὲν τοὺς ἤρεσε. Ὤ, αὐτὸς δὲν ἦτον ἀμανές.

Δὲν ἦτον, ὅπως τὸν ἤξευραν αὐτοί. Ἀλλ' ὁ Δερβίσης τοὺς ἔλεγε τὸν καθ' αὑτὸ ἀμανέν.

⁂
Ἐπανῆλθεν εἰς τὸ καφενεῖον. Τὸ καφενεῖον ἀντικρὺ τοῦ Θησείου. Ἡ ταβέρνα δίπλα εἰς τὸ καφενεῖον. Καὶ τὰ δύο ἀντικρὺ τοῦ παλαιοῦ σταθμοῦ Α. Π. Παραπέρα ἀπὸ τὸ καφενεῖον, ἡ σῆραγξ ἐσκάπτετο, εἶχε σκαφῆ.

Φθινόπωρον τῆς χρονιᾶς ἐκείνης.

Ὁ Δερβίσης ἐκάθητο ἐκεῖ κ' ἔπινε μαστίχαν, ὅποιος τὸν ἐκερνοῦσε. Μὲ τὸ σαρίκι του, μὲ τὰ κατσαρὰ ψαρὰ γένεια του, μὲ τὸ τσιμπούκι του. Ἄνω τῶν 50 ἐτῶν ἡλικίας.

⁂
Ἐκεῖ διενυκτέρευεν ἀπὸ ἡμερῶν. Ἄστεγος, ἀνέστιος, φερέοικος. Τὸ μικρὸν καφενεῖον εἶχε τὴν ἄδειαν νὰ μένῃ ἀνοικτὸν ὅλην τὴν νύκτα.

Ἤρχοντο ἀπὸ τοὺς τζόγους, ἀπὸ τὰ θέατρα, θαμῶνες. Ἤρχοντο ἀπὸ τὸ λαχανοπάζαρον. Ἔπιναν ρούμι καὶ φασκόμηλον.

Ὁ Δερβίσης ἔπαιζε κάποτε τὸ νάϊ. Ὁ κλήτωρ ὁ ἀστυνομικὸς διεσκέδαζεν. Ἀγαποῦσε ν' ἀκούῃ.

Καλὸς ἄνθρωπος. Πρὸ ἐτῶν, ὅταν πρωτοδιωρίσθη, ἦτον γεμάτος ζῆλον.

Ἅμα εἶδε καυγάν, ἔτρεξεν ἀμέσως νὰ τοὺς χωρίσῃ. Εἷς παλαιὸς συνάδελφός του τὸν ᾤκτειρεν.

− Ὅταν βλέπῃς καυγά, νὰ τρέχῃς ἀπὸ τὸ πλαγινὸ σοκάκι, ν' ἀργοπορῇς, ὥς ποὺ νὰ περάσῃ ἡ φούρια, καὶ τότε νὰ παρουσιάζεσαι.

Καὶ ἄλλην συμβουλὴν τοῦ ἔδωκε:

− Στὸν καυγά, πάντοτε νὰ βλέπῃς ποιὸς εἶναι δυνατώτερος καὶ νὰ φυλάγεσαι. Νὰ μαλώνῃς τὸν πιὸ ἀδύνατον, νὰ τοῦ τραβᾷς κ' ἕνα χαστούκι, καὶ νὰ ἐπαναφέρῃς τὴν τάξιν. Ἔτσι θὰ βγαίνῃς λάδι.

Καὶ ἀκόμη:

− Κάθε καινούργιος ἀνώτερος ποὺ διορίζεται τὴν πρώτη μέρα εἶναι γεμᾶτος αὐστηρότητα. Τὸ κάνει γιὰ νὰ τοὺς πάρῃ τὸν ἀέρα. Τὴν δεύτερη μέρα κρυώνει, καὶ τὴν τρίτη μέρα παραδίνεται. Ἐσὺ νὰ συμμορφώνεσαι σύμφωνα μὲ τὸν προϊστάμενον, καὶ νὰ παραπανίζῃς μάλιστα, αὐτὲς τὲς τρεῖς μέρες.

Πολύτιμοι ὑποθῆκαι.

⁂
Τὰς ἡμέρας ἐκείνας εἶχε διορισθῆ νέος ἀστυνόμος.

Διὰ νὰ δείξῃ τὸν ζῆλόν του, διέταξε νὰ κλείσῃ τὸ καφενεῖον, τὴν νύκτα ἐκείνην.

Αὔριον ἢ μεθαύριον θὰ ἐπέτρεπε πάλιν νὰ μένῃ ἀνοικτόν. Ἀλλ' ἡ νὺξ ἐκείνη εἶχε πέσει εἰς τὸν λαχνόν, ἦτο πεπρωμένη νύξ.

Ὁ καλὸς κλήτωρ, ἐνθυμεῖτο τὰς συμβουλὰς τοῦ συναδέλφου του. Ἀνάγκη νὰ βιάσῃ τὸν καφετζὴν νὰ κλείσῃ. Δὲν ἐπετράπη εἰς τὸν βοηθὸν νὰ μείνῃ ἐντός, διὰ νὰ μὴ σηκωθῇ καὶ ἀνοίξῃ εἰς ὅσους ἦτο πιθανὸν νὰ ἔλθουν νὰ κρούσωσι τὴν θύραν. Δὲν ἐπετράπη εἰς τὸν Δερβίσην, τὸν ἀνέστιον, τὸν πλάνητα, νὰ μείνῃ, ἐπὶ τῇ προφάσει ὅτι ἔπαιζε τὸ νάϊ, κ' ἐμάζωνε κόσμον, καὶ δὲν ἄφηνε τοὺς γείτονας νὰ κοιμηθοῦν. Ὁ Δερβίσης μὲ τὸ σαρίκι του, μὲ τὸν τσουμπέν του, μὲ τὸν δουλαμάν του, ἐπῆρε τὸ τσιμπούκι του, τὸ νάϊ του, κ' ἔφυγε.

Ποῦ νὰ ὑπάγῃ;

Ἔκαμεν ὀλίγα βήματα ἀσκόπως, πέριξ τοῦ καφενείου.

Παρέκει ἦτο ἡ σῆραγξ. Ἐσκάπτετο, ἦτο σκαμμένη.

Ἔκαμνε ψύχραν, νυκτερινὸν ἀπόγειον. Μία μετὰ τὰ μεσάνυκτα.

Ὁ κλήτωρ ὁ σκοπὸς περιεφέρετο ὑποκάτω εἰς τὸ κιόσκι, τὸ τσιγκοσκεπές, τῶν ἐκεῖ μαγαζείων.

Ὁ Δερβίσης ὁ πλάνης κατῆλθεν εἰς τὸ βάθος τῆς σήραγγος. Ἴσως ἤλπιζε νὰ εὕρῃ περισσότερον ἀπάγκειο ἐκεῖ.

Ἐκάθισεν, ἀκούμβησεν.

Ἐσκέπτετο τὸ ἄστατον τῶν ἀνθρωπίνων πραγμάτων. Ἄσκ ὀλσοὺν τσιβιρινέκ. Χαρὰ σ' ἐκεῖνον ποὺ ξέρει νὰ τὸν γυρίζῃ, τὸν κόσμον αὐτόν.

⁂
Παρῆλθεν ὥρα. Ὁ κλήτωρ, ὅστις ἐπεριπάτει ἐκεῖ τριγύρω, ἐσκέπτετο τί νὰ εἶχε γίνει ὁ Δερβίσης, τὸν ὁποῖον εἶχεν ἰδεῖ νὰ καταβαίνῃ εἰς τὴν σήραγγα.

Ποῦ νὰ εἶναι;

Εἰς τὴν ἐρώτησιν αὐτὴν τὴν ἄφωνον ἀπήντησε φωνή, ἦχος, μέλος γλυκύ.

Ὁ ξένος μουσουλμάνος εἶχε παγώσει ἐκεῖ ὅπου ἐκαθῆτο κ' ἐνύσταζε. Διὰ νὰ ζεσταθῇ, ἔβγαλε τὸ νάϊ του καὶ ἤρχισε νὰ παίζῃ τὸν τυχόντα ἦχον, ὅστις τοῦ ἦλθε κατ' ἐπιφορὰν εἰς τὴν μνήμην.

Νάϊ, νάϊ, γλυκύ.

Νάζι − κατὰ ἓν ζῆτα ἐλαττοῦται.

Αὔρα, οὐρανός, ᾆσμα γλυκερόν, μελιχρόν, ἁβρόν, μεθυστικόν.

Νάϊ, νάϊ.

Κατὰ δύο κοκκίδας, διαφέρει διὰ νὰ εἶναι τὸ Ναί, ὁποὺ εἶπεν ὁ Χριστός[1].

Τὸ Ναὶ τὸ ἥμερον, τὸ ταπεινόν, τὸ πρᾷον, τὸ Ναὶ τὸ φιλάνθρωπον.

Κάτω εἰς τὸ βάθος, εἰς τὸν λάκκον, εἰς τὸ βάραθρον, ὡς κελάρυσμα ρύακος εἰς τὸ ρεῦμα, φωνὴ ἐκ βαθέως ἀναβαίνουσα, ὡς μύρον, ὡς ἄχνη, ὡς ἀτμός, θρῆνος, πάθος, μελῳδία, ἀνερχομένη ἐπὶ πτίλων αὔρας νυκτερινῆς, αἰρομένη μετάρσιος, πραεῖα, μειλιχία, ἄδολος, ψίθυρος, λιγεῖα, ἀναρριχωμένη εἰς τὰς ριπάς, χορδίζουσα τοὺς ἀέρας, χαιρετίζουσα τὸ ἀχανές, ἱκετεύουσα τὸ ἄπειρον, παιδική, ἄκακος, ἑλισσομένη, φωνὴ παρθένου μοιρολογούσης, μινύρισμα πτηνοῦ χειμαζομένου, λαχταροῦντος τὴν ἐπάνοδον τοῦ ἔαρος.

Τὰ βαρέα τείχη καὶ οἱ ὀγκώδεις κίονες τοῦ Θησείου, ἡ στέγη ἡ μεγαλοβριθής, δὲν ἐξεπλάγησαν πρὸς τὴν φωνήν, πρὸς τὸ μέλος ἐκεῖνο. Τὴν ἐνθυμοῦντο, τὴν ἀνεγνώριζον. Καὶ ἄλλοτε τὴν εἶχον ἀκούσει. Καὶ εἰς τοὺς αἰῶνας τῆς δουλείας καὶ εἰς τοὺς χρόνους τῆς ἀκμῆς.

Ἡ μουσικὴ ἐκείνη δὲν ἦτο τόσον βάρβαρος, ὅσον ὑποτίθεται ὅτι εἶναι τὰ ἀσιατικὰ φῦλα. Εἶχε στενὴν συγγένειαν μὲ τὰς ἀρχαίας ἁρμονίας, τὰς φρυγιστὶ καὶ λυδιστί.

⁂
Ἔφυγαν αἱ βαθεῖα ὧραι, καὶ νὺξ ἦτο ἀκόμη, πεπρωμένη νύξ.

Ἀκόμη ἥπλωνεν αὕτη τὰ σκότη της, καὶ ὁ σαλεπτσὴς ἔκρωζε διὰ νὰ πωλήσῃ τὸ ἐμπόρευμά του, καὶ οἱ πετεινοὶ ἐζάρωναν εἰς τὸν ὀρνιθῶνα. Τὸ μικρὸν παράθυρον ἔτριζε, καὶ ὁ σαλεπτσὴς ἐξηκολούθει τουρκιστὶ τὸν διάλογόν του μὲ τὸν Δερβίσην, τὸν ἄστεγον, τὸν ὑπερόριον.

Πρὸ ὥρας ἤδη εἶχε σιγήσει τὸ ᾆσμα τὸ μυστηριῶδες καὶ μελιχρόν, τὸ νάϊ εἶχε πέσει ἀπὸ τὴν χεῖρα. Ὁ οὐρανός, συννεφώδης, εἶχεν ἀρχίσει νὰ βρέχῃ, ἔβρεξεν ἐπ' ὀλίγα λεπτά, εἶτα ἔπαυσεν. Ὁ κλήτωρ εἶχε γίνει ἄφαντος. Αἱμωδιασμένος, βρεγμένος, κρυωμένος, ὁ Δερβίσης ἀνέβη εἰς τὸν ἐπάνω κόσμον.

Ἐπῆρεν ἕνα δρομίσκον, κατέμπροσθεν τοῦ ἱεροῦ βήματος τῶν Ἁγίων Ἀσωμάτων. Δρομίσκον τὸν ὁποῖον ἡ σεβαστὴ ἐπιτροπὴ εἶχεν ὀνοματίσει, δηλαδὴ εἶχε γράψει ἐπὶ πινακίδος ὅτι εἶναι ὁδὸς Λεπενιώτου.

Ὁ ἴδιος ὁ Λεπενιώτης ὁ λεοντόκαρδος, ὅσον καὶ ἂν ἔτρεφε φιλέκδικον πάθος διὰ τὸν φόνον τοῦ μεγάλου ἥρωος, τοῦ ἀδελφοῦ του, ἀνίσως τὸ πνεῦμά του περιεφοίτα ἐκεῖ, καὶ ἠδύνατο νὰ ἴδῃ τὸν ἄμοιρον Δερβίσην, διωγμένον, ἐξωρισμένον, ἀνέστιον, ριγοῦντα ἀνὰ τὴν στενωπόν, ἕρποντα ἀναμέσον δύο σειρῶν παλαιῶν οἰκίσκων, θὰ τὸν ἐσπλαγχνίζετο.

Καὶ ὁ σαλεπτσὴς τὸν ἐλυπήθη, καὶ ἀντὶ πενταλέπτου τοῦ ἔδωκε νὰ πίῃ σαλέπι διπλοῦν, μισὸ κουλούρι νὰ βουτήξῃ, καὶ ἄφησε τὸν γείτονα μὲ τὸ σάλι, τὸν σηκωθέντα πρὸ μικροῦ ἀπὸ τὴν ζεστὴν κλίνην, νὰ κρυώνῃ περιμένων εἰς τὸ μικρὸν παράθυρον.

− Ἔλα, σαλεπτσή, ποὺ νὰ πάρῃ…
− Μποὺ ντουνιά…

⁂
Τὴν πρωίαν ἐκείνην ἔπιεν ὁ Δερβίσης σαλέπι, ἔφαγε καὶ κουλούρι. Ὅλην τὴν ἡμέραν τὸν ἔπαιρνεν ὁ ὕπνος ὅπου ἐτύχαινε νὰ καθίσῃ.

Τὰς ἄλλας ἡμέρας, ἐξενυχτοῦσεν ἀκόμη εἰς τὸ ὁλονύκτιον καφενεῖον, διὰ τὸ ὁποῖον εἶχε περάσει ἡ πεπρωμένη νύξ. Ἔπινε μαστίχαν κ' ἐκάπνιζε τὸ τσιμπούκι του. Πότε−πότε ἔπαιζεν ἀκόμη τὸ νάϊ.

Ὕστερον, μετ' ὀλίγας ἡμέρας, ἔγινεν ἄφαντος καὶ δὲν τὸν εἶδε πλέον κανείς. Ζῇ, ἀπέθανε, περιπλανᾶται εἰς ἄλλα μέρη, ἀνεκλήθη ἀπὸ τῆς ἐξορίας, ἐπανέκαμψεν εἰς τὸν τόπον του;

Κανεὶς δὲν ἠξεύρει.

Ἴσως τὴν ὥραν ταύτην ν' ἀνέκτησε τὴν εὔνοιαν τοῦ ἰσχυροῦ Παδισάχ, ἴσως νὰ εἶναι μέγας καὶ πολὺς μεταξὺ τῶν Οὐλεμάδων τῆς Σταμπούλ, ἴσως νὰ διαπρέπῃ ὡς ἰμάμης εἰς κανὲν ἐξακουστὸν τζαμίον.

Ἴσως νὰ εἶναι εὐνοούμενος τοῦ Χαλίφη, ἀρχιουλεμάς, σεϊχουλισλάμης.

Μποὺ ντουνιὰ τσὰρκ φιλέκ.

(1896)

** Ο ΞΕΠΕΣΜΕΝΟΣ ΔΕΡΒΙΣΗΣ - μονοτονικά

Δύο, τρεις, πέντε, δέκα σταλαγμοί.
Όμοιοι με το μονότονον βήμα του αγρύπνου ναύτου φρουρού εις την κουβέρταν. Πλέει εις μαύρα πέλαγα και βλέπει ουρανόν και θάλασσαν αγρίως χορεύουσαν, και τυλιγμένος εις την καπόταν του διασχίζει ακαριαίως το σκότος με την εξανάπτουσαν και υποσβήνουσαν λαμπυρίδα του τσιγάρου του.
Οι πετεινοί δεν είχαν λαλήσει το τρίτον λάλημα. Ίσως είχαν τρομάξει από την βαθείαν, θρηνώδη φωνήν του σαλεπτσή, όστις είχεν αρχίσει το φθινόπωρον, νύκτα βαθιά, να κράζει. Ήτο ως κρωγμός αγνώστου ορνέου, το οποίον είχε χάσει τον αέρα του, και είχεν ενσκήψει μέσα εις την πόλιν, κι εζήτει αρπάγματα να σπαράξει.
— Ζεστό ! Βράζει ! …
Έβραζεν, έβραζε, η νύκτα βαθιά. Ζεστόν το σαλέπι, πολύ ζεστότερον το στρώμα. Μόνον η φωνή του σαλεπτσή ετρόμαζε τους πετεινούς.
Είχε βρέξει ολίγον, είτα ηθρίασε. Σταλαγμοί, σταλαγμοί έπεφταν αργά-αργά, από την υδρορρόην εντός της αυλής.

٭٭٭٭
—    Έ ! και πού, σ’ αυτόν τον κόσμο;
Η επιφώνησις ηκούσθη εις το σκότος από το στόμα του σαλεπτσή.
Το παράθυρον έτριξε, κρακ ! από το χαμηλόν δωμάτιον το βλέπον προς τον δρόμον. Άνθρωπος προέκυψε τυλιγμένος με σάλι. Έτεινε μέγαν κύαθον προς τον σαλεπτσήν, αλλ’ ούτος ηργοπόρει.
Ο άνθρωπος έκυψε να ιδεί.
Υψηλή μορφή, με λευκόν σαρίκι, με μαύρην χλαίναν και χιτώνα χρωματιστόν, είχε σταθεί ενώπιον του σαλεπτσή.




—    Πού, σ’ αυτόν τον κόσμο ;
—    Μπου ντουνιά τσαρκ φιλέκ.
—    Άσκ ολσούν … υπεψιθύρισεν ο σαλεπτσής.
Δεν είχε γνωρίσει τον άνθρωπον, αλλά το ένδυμα. Κάθε άλλος θα τον εξελάμβανε ως φάντασμα. Αλλ’ αυτός δεν επτοήθη. Ήτο απ’ εκείνα τα χώματα.

٭٭٭٭

Είχεν αναφανεί. Πότε; Προ ημερών, προ εβδομάδων. Πόθεν; Από την Ρούμελην, από την Ανατολήν, από την Σταμπούλ. Πώς; Εκ ποίας αφορμής; Ποίος;
Ήτον Δερβίσης; Ήτον βεκτασής, χόντζας, ιμάμης; Ήτον ουλεμάς, διαβασμένος; Υψηλός, μελαψός, συμπαθής, γλυκύς, άγριος. Με το σαρίκι του, με τον τσουμπέν του, με τον δουλαμάν του.
Ήτο εις εύνοιαν, εις δυσμένειαν; Είχεν ακμάσει, είχεν εκπέσει, είχεν εξορισθεί; Μπου ντουνιά τσαρκ φιλέκ. Αυτός ο κόσμος είναι σφαίρα και γυρίζει.
Εκείνην την βραδιάν τον είχε προσκαλέσει μία παρέα. Επτά ή οκτώ φίλοι αχώριστοι. Αγαπούσαν την ζωήν, τα νιάτα. Ο ένας απ’ αυτούς έβαλλε γιουβέτσι κάθε βράδυ. Οι άλλοι έτρωγαν.
Ήτον λοταρτζής κι εκέρδιζε δέκα ή δεκαπέντε δραχμάς την ημέραν. Τι να τας κάμει; Τους έβαλλε γιουβέτσι και τους εφίλευε. Ήσαν λοτοφάγοι, με ομικρόν και με ωμέγα.
Αγαπούσαν τα τραγούδια, τα όργανα. Ο Δερβίσης δεν έπινε κρασί, έπινε μαστίχαν. Δερβισάδες ήσαν κι αυτοί. Του είπαν να τραγουδήσει. Ετραγούδησε. Του είπαν να παίξει το νάι. Έπαιξε.
Δεν τους ήρεσε. Ώ, αυτός δεν ήτον αμανές.
Δεν ήτον, όπως τον ήξευραν αυτοί. Αλλ’ ο Δερβίσης τους έλεγε τον καθ’ αυτό αμανέν.

٭٭٭٭

Επανήλθεν εις το καφενείον. Το καφενείον αντικρύ του Θησείου. Η ταβέρνα δίπλα εις το καφενείον. Και τα δύο αντικρύ του παλαιού σταθμού Α. Π. Παραπέρα από το καφενείον,  η σήραγξ εσκάπτετο, είχε σκαφεί. Φθινόπωρον της χρονιάς εκείνης.


Ο Δερβίσης εκάθητο εκεί κι έπινε μαστίχαν, όποιος τον εκερνούσε. Με το σαρίκι του, με τα κατσαρά ψαρά γένεια του, με το τσιμπούκι του. Άνω των 50 ετών ηλικίας.
٭٭٭٭
Εκεί διενυκτέρευεν από ημερών. Άστεγος, ανέστιος, φερέοικος. Το μικρόν καφενείον είχε την άδειαν να μένει ανοικτόν όλην την νύκτα.
Ήρχοντο από τους τζόγους, από τα θέατρα, θαμώνες. Ήρχοντο από το λαχανοπάζαρον. Έπιναν ρούμι και φασκόμηλον.
Ο Δερβίσης έπαιζε κάποτε το νάι. Ο κλήτωρ ο αστυνομικός διεσκέδαζεν. Αγαπούσε ν’ ακούει.
Καλός άνθρωπος. Προ ετών, όταν πρωτοδιωρίσθη, ήτον γεμάτος ζήλον.
Άμα είδε καυγάν, έτρεξεν αμέσως να τους χωρίσει. Εις παλαιός συνάδελφός του τον ώκτειρεν.
— Όταν βλέπεις καυγά, να τρέχεις από το πλαγινό σοκάκι, ν’ αργοπορείς, ως που να περάσει η φούρια, και τότε να παρουσιάζεσαι.
Και άλλην συμβουλήν του έδωκε :
— Στον καυγά, πάντοτε να βλέπεις ποιος είναι δυνατώτερος και να φυλάγεσαι. Να μαλώνεις τον πιο αδύνατον, να του τραβάς κι ένα χαστούκι, και να επαναφέρεις την τάξιν. Έτσι θα βγαίνεις λάδι.
Και ακόμη :
— Κάθε καινούργιος ανώτερος που διορίζεται την πρώτη μέρα είναι γεμάτος αυστηρότητα. Το κάνει για να τους πάρει τον αέρα. Την δεύτερη μέρα κρυώνει, και την τρίτη μέρα παραδίνεται. Εσύ να συμμορφώνεσαι σύμφωνα με τον προϊστάμενον, και να παραπανίζεις μάλιστα, αυτές τες τρεις μέρες.
Πολύτιμοι υποθήκαι.
٭٭٭٭
Τας ημέρας εκείνας είχε διορισθεί νέος αστυνόμος.
Διά να δείξει τον ζήλον του, διέταξε να κλείσει το καφενείον, την νύκτα εκείνην.
Αύριον ή μεθαύριον θα επέτρεπε πάλιν  να μένει ανοικτόν. Αλλ’ η νυξ εκείνη είχε πέσει εις τον λαχνόν, ήτο πεπρωμένη νυξ.
Ο καλός κλήτωρ, ενθυμείτο τας συμβουλάς του συναδέλφου του. Ανάγκη να βιάσει τον καφετζήν να κλείσει. Δεν επετράπη εις τον βοηθόν να μείνει εντός, διά να μη σηκωθεί και ανοίξει εις όσους ήτο πιθανόν να έλθουν να κρούσωσι την θύραν. Δεν επετράπη εις τον Δερβίσην, τον ανέστιον, τον πλάνητα, να μείνει, επί τη προφάσει ότι έπαιζε το νάι, κι εμάζωνε κόσμον, και δεν άφηνε τους γείτονας να κοιμηθούν. Ο Δερβίσης με το σαρίκι του, με τον τσουμπέν του, με τον δουλαμάν  του, επήρε το τσιμπούκι του, το νάι του, κ’ έφυγε.
Πού να υπάγει;
Έκαμεν ολίγα βήματα ασκόπως, πέριξ του καφενείου.
Παρέκει ήτο η σήραγξ. Εσκάπτετο, ήτο σκαμμένη.
Έκαμνε ψύχραν, νυκτερινόν απόγειον. Μία μετά τα μεσάνυκτα.
Ο κλήτωρ ο σκοπός περιεφέρετο υποκάτω εις το κιόσκι, το τσιγκοσκεπές, των εκεί μαγαζείων.
Ο Δερβίσης ο πλάνης κατήλθεν εις το βάθος της σήραγγος. Ίσως ήλπιζε να εύρει περισσότερον απάγκειο εκεί.
Εκάθισεν, ακούμβησεν.
Εσκέπτετο το άστατον των ανθρωπίνων πραγμάτων. Ασκ ολσούν τσιβιρινέκ.  Χαρά σ’ εκείνον που ξέρει να τον γυρίζει, τον κόσμον αυτόν.

٭٭٭٭

Παρήλθεν ώρα. Ο κλήτωρ, όστις επεριπάτει εκεί τριγύρω, εσκέπτετο τι να είχε γίνει ο Δερβίσης, τον οποίον είχεν ιδεί να καταβαίνη εις την σήραγγα.
Πού να είναι;
Εις την ερώτησιν αυτήν την άφωνον απήντησε φωνή, ήχος, μέλος γλυκύ.
Ο ξένος μουσουλμάνος είχε παγώσει εκεί όπου εκάθητο κι ενύσταζε. Διά να ζεσταθεί, έβγαλε το νάι του και ήρχισε να παίζει τον τυχόντα ήχον, όστις του ήλθε κατ’ επιφοράν εις την μνήμην.
Νάι, νάι, γλυκύ.
Νάζι — κατά έν ζήτα ελαττούται.
Αύρα, ουρανός, άσμα γλυκερόν, μελιχρόν, αβρόν, μεθυστικόν.
Νάι, νάι.
Κατά δύο κοκκίδας, διαφέρει διά να είναι το Ναι, οπού είπεν ο Χριστός.
Το Ναι το ήμερον, το ταπεινόν, το πράον, το Ναι το φιλάνθρωπον.
Κάτω εις το βάθος, εις τον λάκκον, εις το βάραθρον, ως κελάρυσμα ρύακος εις το ρεύμα, φωνή εκ βαθέων αναβαίνουσα, ως μύρον, ως άχνη, ως ατμός, θρήνος, πάθος, μελωδία, ανερχομένη επί πτίλων αύρας νυκτερινής, αιρομένη μετάρσιος, πραεία, μειλιχία, άδολος, ψίθυρος, λιγεία, αναρριχωμένη εις τας ριπάς, χορδίζουσα τους αέρας, χαιρετίζουσα το αχανές, ικετεύουσα το άπειρον, παιδική, άκακος, ελισσομένη, φωνή παρθένου μοιρολογούσης, μινύρισμα πτηνού χειμαζομένου, λαχταρούντος την επάνοδον του έαρος.
Τα βαρέα τείχη και οι ογκώδεις κίονες του Θησείου, η στέγη η μεγαλοβριθής, δεν εξεπλάγησαν προς την φωνήν, προς το μέλος εκείνο. Την ενθυμούντο, την ανεγνώριζον. Και άλλοτε την είχον ακούσει. Και εις τους αιώνας της δουλείας και εις τους χρόνους της ακμής.
Η μουσική εκείνη δεν ήτο τόσον βάρβαρος, όσον υποτίθεται ότι είναι τα αστιατικά φύλα. Είχε στενήν συγγένειαν με τας αρχαίας αρμονίας, τας φρυγιστί και λυδιστί.
٭٭٭٭

Έφυγαν αι βαθείαι ώραι, και νυξ ήτο ακόμη, πεπρωμένη νυξ.
Ακόμη ήπλωνεν αύτη τα σκότη της, και ο σαλεπτσής έκρωζε διά να πωλήσει το εμπόρευμά του, και οι πετεινοί εζάρωναν εις τον ορνιθώνα. Το μικρόν παράθυρον έτριζε, και ο σαλεπτσής εξηκολούθει τουρκιστί τον διάλογόν του με τον Δερβίση, τον άστεγον, τον υπερόριον.
Προ ώρας ήδη είχε σιγήσει το άσμα το μυστηριώδες και μελιχρόν, το νάι είχε πέσει από την χείρα. Ο ουρανός, συννεφώδης, είχεν αρχίσει να βρέχει, έβρεξεν επ’ ολίγα λεπτά, είτα έπαυσεν. Ο κλήτωρ είχε γίνει άφαντος. Αιμωδιασμένος, βρεγμένος, κρυωμένος, ο Δερβίσης ανέβη εις τον επάνω κόσμον.
Επήρεν ένα δρομίσκον, κατέμπροσθεν του ιερού βήματος των Αγίων Ασωμάτων. Δρομίσκον τον οποίον η σεβαστή επιτροπή είχεν ονοματίσει, δηλαδή είχε γράψει επί πινακίδος ότι είναι οδός Λεπενιώτου.
Ο ίδιος ο Λεπενιώτης ο λεοντόκαρδος, όσον και αν έτρεφε φιλέκδικον πάθος διά τον φόνον του μεγάλου ήρωος, του αδελφού του, ανίσως το πνεύμα του περιεφοίτα εκεί, και ηδύνατο να ίδει τον άμοιρον Δερβίσην, διωγμένον, εξωρισμένον, ανέστιον, ριγούντα ανά την στενωπόν, έρποντα αναμέσον δύο σειρών παλαιών οικίσκων, θα τον εσπλαγχνίζετο.
Και ο σαλεπτσής τον ελυπήθη, και αντί πενταλέπτου του έδωκε να πίει σαλέπι διπλούν, μισό κουλούρι να βουτήξει, και άφησε τον γείτονα με το σάλι, τον σηκωθέντα προ μικρού από την ζεστήν κλίνην, να κρυώνει περιμένων εις το μικρόν παράθυρον.
—  Έλα, σαλεπτσή, που να πάρει …
—    Μπου ντουνιά …

٭٭٭٭

Την πρωίαν εκείνην έπιεν ο Δερβίσης σαλέπι, έφαγε και κουλούρι.  Όλην την ημέραν τον έπαιρνε ο ύπνος όπου ετύχαινε να καθίσει.
Τας άλλας ημέρας, εξενυχτούσεν ακόμη εις το ολονύκτιον καφενείον, διά το οποίον είχε περάσει η πεπρωμένη νυξ. Έπινε μαστίχαν κι εκάπνιζε το τσιμπούκι του. Πότε-πότε έπαιζεν ακόμη το νάι.
Ύστερον, μετ’ ολίγας ημέρας, έγινεν άφαντος και δεν τον είδε πλέον κανείς. Ζει, απέθανε, περιπλανάται εις άλλα μέρη, ανεκλήθη από της εξορίας, επανέκαμψεν εις τον τόπον του;
Κανείς δεν ηξεύρει.
Ίσως την ώραν ταύτην ν’ ανέκτησε την εύνοιαν του ισχυρού Παδισάχ, ίσως να είναι μέγας και πολύς μεταξύ των Ουλεμάδων της Σταμπούλ, ίσως να διαπρέπει ως ιμάμης εις κανέν εξακουστόν τζαμίον.
Ίσως να είναι ευνοούμενος του Χαλίφη, αρχιουλεμάς, σεϊχουλισλάμης.
Μπου ντουνιά τσαρκ φιλέκ.

(1896)


Το πήρα από την κριτική έκδοση του Ν. Δ. Τριανταφυλλόπουλου και εκσυγχρόνισα λίγο ακόμα την ορθογραφία (μονοτονικό, υποτακτική). Η σημερινή γραφή δημιουργεί πρόβλημα στο σημείο όπου ο Παπαδιαμάντης γράφει πως το «νάι» (που γραφόταν «νάϊ» τότε) απέχει δύο κουκίδες από το «ναι» (που γραφόταν «ναί»).

Η τουρκική παροιμία Μπου ντουνιά τσαρκ φιλέκ, την οποία ο Ππδ. εξηγεί «Αυτός ο κόσμος είναι σφαίρα και γυρίζει» σημαίνει ακριβέστερα «Αυτός ο κόσμος είναι τροχός της τύχης». Το felek (εξ ου και το φελέκι) είναι η τύχη.
Ο δουλεμάς είναι είδος επενδύτη, ο ουλεμάς είναι ο απόφοιτος της ιερονομικής σχολής, σεϊχουλισλάμης ήταν ο ανώτερος θρησκευτικός λειτουργός στην Οθωμανική αυτοκρατορία (όλα αυτά σύμφωνα με το Γλωσσάρι της κριτικής έκδοσης).

* Ανάλυση
(απο αμμόχωστο σαιτ)

« /Ο ξεπεσμένος Δερβίσης/ » είναι το καλύτερο αθηναϊκό διήγημα του Α. Παπαδιαμάντη. Δημοσιεύτηκε τον Ιανουάριο του 1896. *Μέσα από αυτό ο Παπαδιαμάντης εκφράζει τη συμπάθεια του προς ένα ξένο, αλλόθρησκο και αλλοεθνή, ένα Δερβίση*.

/Ο Δερβίσης, όπως συμπεραίνει κανείς από το διήγημα, καταγόταν «από την Ρούμελην, από την την Ανατολήν, από  την Σταμπούλ»[1].  Είναι άγνωστο γιατί ήρθε στην Αθήνα. Φαίνεται από τη συνάφεια του κειμένου ότι για κάποιο λόγο, είχε εξοριστεί. Ήταν λοιπόν ένας «ξεπεσμένος» Δερβίσης. Μια παρέα από επτά ή οκτώ φίλους τον προσκαλούν σε δείπνο. Συμπονούν τον ξένο και αλλόθρησκο Δερβίση[2]./

Ο Δερβίσης τους διηγήματος διανυκτέρευε σε ένα ολονύκτιο καφενείο. Είχε βρει καταφύγιο εκεί. Εκεί έπαιζε και το νάϊ του. Ήταν λοιπόν άστεγος, άφραγκος και καταφεύγει σε  ένα καφενείο, το οποίο είχε την άδεια να μένει ανοικτό όλο το βράδυ[3]. Είναι ξεκάθαρο ότι ο Παπαδιαμάντης δείχνει τη συμπάθεια του προς τον αλλόθρησκο Δερβίση, προς το ξένο μουσουλμάνο. Με τη στάση του αυτή μας θυμίζει τα λόγια του Χριστού στην παραβολή της κρίσεως «ήμουν ξένος και με περιμαζέψατε…»[4]. Μας θυμίζει ακόμη τη φροντίδα του αλλοεθνή Σαμαρείτη[5]  προς τον τραυματισμένο Ιουδαίο. Τη θετική αυτή στάση προς το Δερβίση, συναντάμε σε ολόκληρο το διήγημα.

Όπως σημειώσαμε, ο Δερβίσης διανυκτέρευε σε ένα καφενείο. Κάποια στιγμή όμως διορίζεται στην περιοχή νέος αστυνόμος. Αυτός, για να δείξει το ζήλο του, διέταξε μια συγκεκριμένη νύχτα να κλείσει το ολονύκτιο καφενείο. Αυτό σήμαινε βέβαια ότι ο Δερβίσης έμενε άστεγος, εκτεθειμένος στο κρύο[6]. Ο Παπαδιαμάντης όμως φροντίζει για τον Δερβίση, καίτοι αυτός ήταν ξένος και μουσουλμάνος. Εκεί κοντά είχαν σκάψει μια σήραγγα. Σε αυτήν βρίσκει τώρα καταφύγιο ο Δερβίσης, προκειμένου να προστατευθεί από το κρύο και να ξεκουραστεί το βράδυ. Για να ζεσταθεί, αλλά και να περάσει την ώρα του, έβγαλε το νάϊ του και άρχισε να παίζει. Τότε, μια γλυκιά μελωδία έβγαινε από τη σήραγγα[7]. Τα όσα γράφει στη συνέχεια ο Παπαδιαμάντης, επιβεβαιώνουν τα όσα προηγουμένως επισημάναμε, τη συμπάθεια του δηλαδή προς τον αλλόθρησκο Δερβίση: «Νάϊ, νάϊ. Κατά δίο κοκκίδας, διαφέρει δια να είναι το Ναι, όπου είπεν ο Χριστός. Το ναι το ήμερον, το ταπεινόν, το πράν, το Ναι το φιλάνθρωπον»[8]. Ο Παπαδιαμάντης βλέπει στο πρόσωπο του ξένου μουσουλμάνου, τον πάσχοντα συνάνθρωπο μας, τον αδελφό μας και τελικά, θα λέγαμε, τον ίδιο τον Χριστό, αφού ο ίδιος ο Κύριος στην παραβολή της κρίσεως αποκαλεί «αδελφούς» του όλους τους πάσχοντες και αναξιοπαθούντες[9].

Ο Στέλιος Παπαθανασίου για τα πιο πάνω κάνει ένα συσχετισμό – παραλληλισμό. Ο Δερβίσης παίζει με το νάϊ του ένα άσμα. Εάν μετακινηθούμε από το διήγημα αυτό του Παπαδιαμάντη και πάμε στο «Ασματικόν» του Όρθρου του Μεγάλου Σαββάτου, θα δούμε εκεί τον Ιωσήφ τον από Αριμαθαίας, να ζητά «τον ξένον», δηλαδή τον Χριστό, από τον Πιλάτο, προκειμένου να τον «κρύψει» στον τάφο, δηλαδή να τον ενταφιάσει. Έτσι και ο Παπαδιαμάντης πράττει στο διήγημα του το ορθόδοξα αυτονόητο. «Κρύβει» τον άστεγο, φτωχό και ξένο αλλόθρησκο σε ένα «τάφο», δηλαδή στο βάθος της σήραγγας[10].

Στη συνέχεια του διηγήματος, ο Παπαδιαμάντης, προσφέρει τροφή στον πένητα ξένο. Ο σαλεπτσής λυπάται τον φτωχό Δερβίση και του δίνει να πιεί σαλέπι και κουλούρι για να φάει[11]. Και πάλι εδώ έρχονται στο μυαλό μας τα λόγια του Κυρίου «πείνασα και μου δώσατε να φάω, δίψασα και μου δώσατε να πιώ»[12]. Η συμπάθεια προς ένα ξένο και δη τούρκο μουσουλμάνο είναι όντως εντυπωσιακή. Ίσως ακόμη και να μας εκπλήσσει. Είναι όμως η ορθή και ορθόδοξη στάση. Είναι η χριστιανική αγάπη που δεν γνωρίζει όρια και φραγμούς.

Στα σημείο αυτό θα επιχειρήσουμε μια συσχέτιση της στάσης έναντι του Ισλάμ, στο διήγημα του Παπαδιαμάντη «Ο ξεπεσμένος Δερβίσης», με τις τάσεις και στάσεις που υπήρξαν κατά καιρούς έναντι της άλλης πίστης.  Πιστεύουμε ότι ανταποκρίνεται, το πιο πάνω διήγημα του Παπαδιαμάντη, στη φάση του χριστιανο – ισλαμικού διαλόγου. Της συνάντησης της Ορθοδοξίας με το Ισλάμ, της αποδοχής της ετερότητας και γενικά της γνωριμίας των δύο θρησκειών και πίστεων[13].

Η φάση αυτή αφορά τη νεώτερη και πολύ περισσότερο τη σύγχρονη εποχή. Ιδιαίτερα μετά το τέλος του 19ου αιώνα, ο διάλογος προωθείται από πανεπιστημιακούς κύκλους, επιστημονικά κέντρα και εκπροσώπους των δύο θρησκειών. Τον 20ο αιώνα σημαντικοί σταθμοί υπήρξαν η Β΄ Βατικάνεια Σύνοδος και ο διαθρησκειακός διάλογος, ο οποίος άρχισε και συνεχίζεται ως τις μέρες μας, με πρωτοβουλία του Παγκοσμίου Συμβουλίου Εκκλησιών[14].

Μετά από έρευνα των τελευταίων 150 ετών γύρω από το Ισλάμ, έχουν παραμεριστεί σοβαρές παρανοήσεις από μέρους των χριστιανών και δη των Ορθοδόξων σχετικά με τη μουσουλμανική πίστη. Γενικά η χριστιανική πλευρά έχει αλλάξει στάση και διάθεση. Πολλοί χριστιανοί αναγνωρίζουν τη δυναμική του Ισλάμ μέσα στην ιστορία και τους πνευματικούς και πολιτιστικούς του θησαυρούς[15].

Το διήγημα «Ο ξεπεσμένος Δερβίσης» ουσιαστικά αποτελεί ένα κάλεσμα προς τους χριστιανούς, αλλά και τους μουσουλμάνους, ώστε να έρθουν πιο κοντά δια του διαλόγου και της αποδοχής της ετερότητας, αλλά και του αλληλοσεβασμού. Όλοι μας, σε όποια πίστη και θρησκεία και αν ανήκουμε, έχουμε να προσφέρουμε πολλά για ένα καλύτερο αύριο. Για αν γίνει όμως αυτό χρειάζεται αποδοχή του άλλου και όχι φανατισμός και μισαλλοδοξία.

* Footnotes

[1] Α. Παπαδιαμάντη, «Ο ξεπεσμένος Δερβίσης», από  Άπαντα του Παπαδιαμάντη, τόμος Γ΄ (επιμ. Ν. Δ. Τριανταφυλλόπουλου, εκδόσεις Δομός, Αθήνα 1984), από Ηλεκτρονική Βιβλιοθήκη Παιδαγωγικού Ινστιτούτου, σελ. 14.
[2] Α. Παπαδιαμάντη, Στο ίδιο, σελ. 14.
[3] Α. Παπαδιαμάντη, Ο. π., σελ. 16-18.
[4] Μτθ. 25, 35.
[5] Λκ. 10, 30-37.
[6] Α. Παπαδιαμάντη, Ο. π., σελ. 20.
[7] Α. Παπαδιαμάντη, Ο. π., σελ. 22-24.
[8] Α. Παπαδιαμάντη, Ο. π., σελ. 26.
[9] Μτθ. 25, 40 και 25, 45.
[10] Σ. Παπαθανασίου, Ο ξεπεσμένος Δερβίσης και ο θρίαμβος της ετερότητας, από Ηλεκτρονική Βιβλιοθήκη Παιδαγωγικού Ινστιτούτου, σελ. 13-14.
[11] Α. Παπαδιαμάντη, Ο.π., σελ 30.
[12] Μτθ. 25, 35.
[13] Α. Γιαννουλάτου, «Ο διάλογος με το Ισλάμ από Ορθόδοξη άποψη», από το βιβλίο Παγκοσμιότητα και Ορθοδοξία, (εκδόσεις Ακρίτας, Αθήνα 2000), σελ. 154.
[14] Α. Γιαννουλάτου, Στο ίδιο, σελ. 154-155.
[15] Α. Γιαννουλάτου, Ο.π., σελ 156.
